
on:
  pull_request:
    types:
      - closed
nv:
  AZURE_WEBAPP_NAME: rewardportal-staging    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.x'                # set this to the node version to us

permissions:
  contents: read

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        echo The PR was merged