on:
  push:
    branches: [ "feature" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: rewardportal-staging    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3