on:
  pull_request:
    branches:
      - development
    types: [closed]

env:
  AZURE_WEBAPP_NAME: rewardportal-development   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    steps:
      - name: Build
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3

          - name: Set up Node.js
            uses: actions/setup-node@v3
            with:
              node-version: ${{ env.NODE_VERSION }}
              cache: 'npm'

          - name: npm install and build
            run: |
              npm install
              npm run build --if-present

          - name: Upload artifact for deployment job
            uses: actions/upload-artifact@v3
            with:
              name: node-app
              path: build

      - name: Deploy
        permissions:
          contents: none
        runs-on: ubuntu-latest
        needs: Build
        environment:
          name: 'Development'
          url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
          - name: Download artifact from build job
            uses: actions/download-artifact@v3
            with:
              name: node-app

          - name: 'Deploy to Azure WebApp'
            id: deploy-to-webapp
            uses: azure/webapps-deploy@v2
            with:
              app-name: ${{ env.AZURE_WEBAPP_NAME }}
              publish-profile: ${{ secrets.AZURE_WEBAPP_REWARD_PORTAL_DEVELOPMENT }}
              package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
